### ISSUE TITLE
Error while selecting the 15th option (collect anyone followers list)

### ISSUE THREAD

**Issue by aditya-pushkar** [sureshpandiyan1/instagram-scraper-it#6]
**Describe the bug**
Error while selecting the 15th option (collect anyone followers list)

**To Reproduce**
1. Go to 'dir'
2. run 'python3 main.py

**Error**

```
choose your option => 15
Traceback (most recent call last):
  File "/Users/Desktop/instabot/instagram-scraper-it/main.py", line 423, in <module>
    insta_svc()
  File "/Users/Desktop/instabot/instagram-scraper-it/main.py", line 95, in insta_svc
    collect_anyone_followers_list()
  File "/Users/Desktop/instabot/instagram-scraper-it/main.py", line 344, in collect_anyone_followers_list
    cnt_mx = followers_counts / 12
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Desktop (please complete the following information):**
 - OS: [mac]
 - Browser [chrome]
 - Version [106.0.5249.119]

**Comment by sureshpandiyan1** [comment]
in followersid.py

first you should the place valid values in followers_count and target_insta_id, before you choose option 15

your every value should be integer, but not a string
```

Example:
followers_counts = 100
target_insta_id = 123213123
```

**Comment by aditya-pushkar** [comment]
@sureshpandiyan1 Thank you very much for quick reponse, just whanted to know what is target_insta_id, is it the username for the scraping insta acount  or something else?

**Comment by sureshpandiyan1** [comment]
choose option 1.. enter your instagram user name..you will get instaid...

**Comment by aditya-pushkar** [comment]
@sureshpandiyan1 what is your email ?

**Comment by sureshpandiyan1** [comment]
> @sureshpandiyan1 what is your email ?

Do u download GitHub repo again?

**Comment by aditya-pushkar** [comment]
yes, I update the repo but still facing the same problem.
let's say I have to scrape the followers of this account then what will be the process .

**Comment by sureshpandiyan1** [comment]
> yes, I update the repo but still facing the same problem.
> let's say I have to scrape the followers of this account then what will be the process .

Screenshot please

**Comment by aditya-pushkar** [comment]
```
Traceback (most recent call last):
  File "/Users/aditya/Desktop/instabot/instagram-scraper-it/main.py", line 544, in <module>
    insta_svc()
  File "/Users/aditya/Desktop/instabot/instagram-scraper-it/main.py", line 96, in insta_svc
    collect_anyone_followers_list()
  File "/Users/aditya/Desktop/instabot/instagram-scraper-it/main.py", line 453, in collect_anyone_followers_list
    i = tk['next_max_id']
KeyError: 'next_max_id'
```
<img width="1209" alt="Screenshot 2022-10-18 at 10 49 13 PM" src="https://user-images.githubusercontent.com/70275567/196500735-17a37683-be86-402f-8552-a4abe2a1b028.png">
<img width="1440" alt="Screenshot 2022-10-18 at 10 49 36 PM" src="https://user-images.githubusercontent.com/70275567/196500769-28fabefc-b17a-4546-a365-9db107738c01.png">

**Comment by aditya-pushkar** [comment]
If we can talk via email, I have some paid work. Let me know
